services:

 postgres:
  image: postgres:13
  container_name: ${POSTGRES_CONTAINER_NAME}
  restart: unless-stopped
  hostname: ${POSTGRES_CONTAINER_NAME}
  environment:
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_DB=${POSTGRES_DB}
   - PGDATA=/var/lib/postgresql/data/pgdata
  volumes:
   - ../database:/database
   - ../data:/data
  ports:
   - ${POSTGRES_PORT}:5432

networks:
 default:
  name: NTX-Network 
  external: true